export type Language = 'en' | 'ar';

export const translations = {
  en: {
    app_name: "Htect",
    disclaimer_title: "Medical Disclaimer & Consent",
    disclaimer_body: "This app is EXPERIMENTAL and for EDUCATIONAL/RESEARCH USE ONLY. It is NOT a medical device, NOT for clinical diagnosis, and NOT a substitute for professional medical advice, radiology interpretation, or treatment. AI results can be inaccurate or misleading. Always consult a licensed physician or radiologist.",
    disclaimer_agreement: "I acknowledge this and accept full responsibility.",
    proceed: "Proceed",
    upload_title: "Upload X-ray or MRI",
    upload_subtitle: "Select an image from your device to begin analysis",
    analyzing: "Analyzing Image...",
    results_title: "Analysis Results",
    confidence: "Confidence",
    severity_low: "Low Priority",
    severity_medium: "Medium Priority",
    severity_high: "High Priority",
    learn_more: "Learn More",
    new_analysis: "New Analysis",
    history_title: "Recent Analyses",
    no_history: "No past analyses found",
    storage_consent: "Save analysis history on this device",
    delete_history: "Clear History",
    history_item_date: "Analyzed on",
    ai_warning: "AI-generated suggestions only — not a diagnosis. See a doctor.",
    feedback_prompt: "Was this helpful?",
    feedback_placeholder: "Tell us more (optional)...",
    feedback_submit: "Submit Feedback",
    feedback_success: "Thank you for your feedback!",
    select_image: "Select Image",
    camera: "Take Photo",
    gallery: "Choose from Gallery",
    error_generic: "Something went wrong. Please try again.",
    error_no_api_key: "API Key is missing. Please configure it in the secrets panel.",
    error_analysis_failed: "The AI service could not process the image. Please try again.",
    error_invalid_image: "The image format is not supported or the file is too large.",
    error_quota: "API quota exceeded. Please try again in a few minutes.",
    theme_light: "Light Mode",
    theme_dark: "Dark Mode",
    listen_summary: "Listen to Summary",
    chat_title: "Ask a Question",
    chat_placeholder: "Ask about this scan...",
    chat_send: "Send",
    chat_loading: "Thinking...",
    quality_check_title: "Image Quality Check",
    quality_check_loading: "Validating image quality...",
    error_blurry: "Image is too blurry. Please retake.",
    error_lighting: "Poor lighting detected. Please use a brighter environment.",
    error_framing: "Incorrect framing. Ensure the scan is centered.",
    compare_with_previous: "Compare with Previous Scan",
    timeline_title: "Progress Timeline",
    recovery_percentage: "Recovery Progress",
    trend_improving: "Improving",
    trend_stable: "Stable",
    trend_declining: "Declining",
    reports_title: "Physician Liaison",
    doctor_note_btn: "Generate Doctor's Note",
    patient_plan_btn: "View Patient Action Plan",
    doctor_note_title: "Professional Medical Summary",
    patient_plan_title: "Patient Action Plan",
    suggested_questions: "Suggested Questions for your Doctor",
    glossary_title: "Medical Terminology",
    share_btn: "Share Results",
    share_disclaimer: "This is an AI summary for informational use only.",
    share_subject: "Htect Medical Scan Analysis",
    close: "Close",
  },
  ar: {
    app_name: "إتش تيك",
    disclaimer_title: "إخلاء مسؤولية طبية وموافقة",
    disclaimer_body: "هذا التطبيق تجريبي ولأغراض التعليم والبحث فقط. إنه ليس جهازًا طبيًا، وليس للتشخيص السريري، وليس بديلاً عن الاستشارة الطبية المهنية أو تفسير الأشعة أو العلاج. يمكن أن تكون نتائج الذكاء الاصطناعي غير دقيقة أو مضللة. استشر دائمًا طبيبًا مرخصًا أو أخصائي أشعة.",
    disclaimer_agreement: "أقر بذلك وأتحمل المسؤولية الكاملة.",
    proceed: "متابعة",
    upload_title: "تحميل صورة أشعة سينية أو رنين مغناطيسي",
    upload_subtitle: "اختر صورة من جهازك لبدء التحليل",
    analyzing: "جاري تحليل الصورة...",
    results_title: "نتائج التحليل",
    confidence: "الثقة",
    severity_low: "أولوية منخفضة",
    severity_medium: "أولوية متوسطة",
    severity_high: "أولوية عالية",
    learn_more: "اقرأ المزيد",
    new_analysis: "تحليل جديد",
    history_title: "التحليلات السابقة",
    no_history: "لم يتم العثور على تحليلات سابقة",
    storage_consent: "حفظ سجل التحليلات على هذا الجهاز",
    delete_history: "مسح السجل",
    history_item_date: "تم التحليل في",
    ai_warning: "اقتراحات ناتجة عن الذكاء الاصطناعي فقط - ليست تشخيصاً. راجع الطبيب.",
    feedback_prompt: "هل كان هذا مفيداً؟",
    feedback_placeholder: "أخبرنا المزيد (اختياري)...",
    feedback_submit: "إرسال الملاحظات",
    feedback_success: "شكراً لملاحظاتك!",
    select_image: "اختر صورة",
    camera: "التقاط صورة",
    gallery: "اختر من المعرض",
    error_generic: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    error_no_api_key: "مفتاح API مفقود. يرجى تهيئته في لوحة الأسرار.",
    error_analysis_failed: "تعذر على خدمة الذكاء الاصطناعي معالجة الصورة. يرجى المحاولة مرة أخرى.",
    error_invalid_image: "تنسيق الصورة غير مدعوم أو الملف كبير جداً.",
    error_quota: "تم تجاوز حصة API. يرجى المحاولة مرة أخرى بعد بضع دقائق.",
    theme_light: "الوضع الفاتح",
    theme_dark: "الوضع الداكن",
    listen_summary: "استمع إلى الملخص",
    chat_title: "اسأل سؤالاً",
    chat_placeholder: "اسأل عن هذا المسح...",
    chat_send: "إرسال",
    chat_loading: "يفكر...",
    quality_check_title: "فحص جودة الصورة",
    quality_check_loading: "جاري التحقق من جودة الصورة...",
    error_blurry: "الصورة غير واضحة جداً. يرجى إعادة الالتقاط.",
    error_lighting: "تم اكتشاف إضاءة ضعيفة. يرجى استخدام بيئة أكثر إشراقاً.",
    error_framing: "تأطير غير صحيح. تأكد من توسيط المسح.",
    compare_with_previous: "مقارنة مع المسح السابق",
    timeline_title: "جدول التقدم الزمني",
    recovery_percentage: "نسبة التعافي",
    trend_improving: "تحسن",
    trend_stable: "مستقر",
    trend_declining: "تراجع",
    reports_title: "منسق الطبيب",
    doctor_note_btn: "إنشاء ملاحظة الطبيب",
    patient_plan_btn: "عرض خطة عمل المريض",
    doctor_note_title: "ملخص طبي احترافي",
    patient_plan_title: "خطة عمل المريض",
    suggested_questions: "أسئلة مقترحة لطبيبك",
    glossary_title: "المصطلحات الطبية",
    share_btn: "مشاركة النتائج",
    share_disclaimer: "هذا ملخص ذكاء اصطناعي للاستخدام المعلوماتي فقط.",
    share_subject: "تحليل مسح إتش تيك الطبي",
    close: "إغلاق",
  }
};
